const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const source=fs.readFileSync('app.js','utf8');
function fn(name){const start=source.indexOf(`function ${name}(`);let pos=source.indexOf('{',start),depth=1,end=pos+1;while(depth){if(source[end]==='{')depth++;if(source[end]==='}')depth--;end++;}return source.slice(start,end);}
test('theme sets persisted preference and accessible toggle state',()=>{const button={setAttribute(k,v){this[k]=v}};const context={document:{documentElement:{dataset:{}}},localStorage:{setItem(k,v){this[k]=v}},$:()=>button};vm.createContext(context);vm.runInContext(fn('setTheme')+';setTheme("dark")',context);assert.equal(context.document.documentElement.dataset.theme,'dark');assert.equal(context.localStorage['yejian-theme'],'dark');assert.equal(button['aria-pressed'],'true');vm.runInContext('setTheme("light")',context);assert.equal(button['aria-pressed'],'false');});
test('collapsed selection hides toolbar without losing question context',()=>{let hidden=false;const context={window:{getSelection:()=>({isCollapsed:true,rangeCount:1})},hideSelectionToolbar:()=>hidden=true};vm.createContext(context);vm.runInContext(fn('captureSelection')+';captureSelection()',context);assert.equal(hidden,true);});
test('highlight excludes parent rectangles and clips text rectangles to page',()=>{const node={textContent:'abc',length:3};let count=0;const context={NodeFilter:{SHOW_TEXT:4},document:{createTreeWalker:()=>({nextNode:()=>++count===1,currentNode:node}),createRange:()=>({setStart(){},setEnd(){},getClientRects:()=>[{left:90,top:110,right:150,bottom:130}]})}};vm.createContext(context);context.range={intersectsNode:()=>true,startContainer:node,endContainer:node,startOffset:0,endOffset:3};context.shell={getBoundingClientRect:()=>({left:100,top:100,right:200,bottom:200,width:100,height:100}),querySelector:()=>({})};vm.runInContext(fn('selectionRects')+';result=selectionRects(range,shell)',context);assert.equal(context.result.length,1);assert.equal(context.result[0].left,0);assert.equal(context.result[0].width,.5);});
test('reading position records normalized offset for zoom independent return',()=>{const button={disabled:true};const context={readingHistory:[],state:{page:3},pageShellForNumber:()=>({clientHeight:1000,getBoundingClientRect:()=>({top:-180})}),els:{pdfViewport:{getBoundingClientRect:()=>({top:100})}},$:()=>button};vm.createContext(context);vm.runInContext(fn('rememberReadingPosition')+';rememberReadingPosition()',context);assert.equal(context.readingHistory[0].page,3);assert.equal(context.readingHistory[0].offset,.3);assert.equal(button.disabled,false);});
test('deleting highlight removes only that annotation, saves and redraws its page',()=>{let saved=false,redrawn=false;const shell={};const context={state:{annotations:[{id:'a',type:'highlight',page:4},{id:'b',type:'note',page:4}]},saveAnnotations:()=>saved=true,pageShellForNumber:p=>{assert.equal(p,4);return shell},renderHighlights:s=>{assert.equal(s,shell);redrawn=true},toast:()=>{}};vm.createContext(context);vm.runInContext(fn('removeAnnotation')+';removeAnnotation("a")',context);assert.equal(context.state.annotations.length,1);assert.equal(context.state.annotations[0].id,'b');assert.ok(saved&&redrawn);});
